<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_link_length" value="0.8" />
    <xacro:property name="base_link_width" value="0.5" />
    <xacro:property name="base_link_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <link name="base_link">
        <!-- <visual name='base_link'>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://my_robot_description/meshes/camello_shell.dae" scale="1 1 1">
                </mesh>
            </geometry>
        </visual> -->
        <visual>
            <geometry>
                <box size="${base_link_length} ${base_link_width} ${base_link_height}" />
            </geometry>
            <origin xyz="0 0 ${base_link_height/2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_link_length} ${base_link_width} ${base_link_height}" />
            </geometry>
            <origin xyz="0 0 ${base_link_height/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_link_length}" y="${base_link_width}"
            z="${base_link_height}" o_xyz="0 0 ${base_link_height/2.0}" o_rpy="0 0 0" />
    </link>
    <link name="second_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.05" />
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="0.2 0.2 0.2" />
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="1.0" x="0.2" y="0.2"
            z="0.2" o_xyz="0 0 0.1" o_rpy="0 0 0" />
    </link>
    <link name="third_link">
        <visual>
            <geometry>
                <box size="${base_link_length-0.3} ${base_link_width-0.3} ${base_link_height-0.3}" />
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1" />
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="1.0" x="0.1" y="0.1"
            z="0.1" o_xyz="0 0 0.05" o_rpy="0 0 0" />
    </link>

    <link name="right_rear_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:wheel_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0"
            o_rpy="${pi/2.0} 0 0" />
    </link>

    <link name="right_front_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:wheel_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0"
            o_rpy="${pi/2.0} 0 0" />
    </link>

    <link name="left_rear_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:wheel_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0"
            o_rpy="${pi/2.0} 0 0" />
    </link>

    <link name="left_front_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:wheel_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0"
            o_rpy="${pi/2.0} 0 0" />
    </link>

    <joint name="base_second_joint" type="fixed">
        <parent link="base_link" />
        <child link="second_link" />
        <origin xyz="${base_link_length/2.0} 0 ${base_link_height}" rpy="0 0 0" />
        <!-- <axis xyz="0 0 1"/>
        <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/> -->
    </joint>
    <!-- <joint name="base_third_joint" type="revolute">
        <parent link="second_link"/>
        <child link="third_link"/>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
    </joint> -->

    <!-- <joint name="base_third_joint" type="continuous">
        <parent link="second_link"/>
        <child link="third_link"/>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint> -->

    <joint name="base_third_joint" type="prismatic">
        <parent link="base_link"/>
        <child link="third_link"/>
        <origin xyz="0 0 ${base_link_height-0.2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="0.0" upper="0.2" effort="150" velocity="0.4"/>
        <dynamics damping="5.0" friction="0.0"/>
    </joint>

    <!-- Adding a Wheel -->
    <joint name="base_right_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_rear_wheel_link" />
        <origin xyz="${-base_link_length/4.0} ${-base_link_width/2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_front_wheel_link" />
        <origin xyz="${base_link_length/4.0} ${-base_link_width/2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_rear_wheel_link" />
        <origin xyz="${-base_link_length/4.0} ${base_link_width/2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_front_wheel_link" />
        <origin xyz="${base_link_length/4.0} ${base_link_width/2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
</robot>